### ISSUE TITLE
Signing does not work

### ISSUE THREAD

**Issue by Quillraven** [Quillraven/Fleks#109]
@aSemy seems like the environment variables in the publish workflow are not properly read from the secrets? Looks like they are all null and that's why the signing fails?

Can you please have a look when you have time?

**Comment by aSemy** [comment]
Ah that sucks. It's frustrating when the GitHub Actions don't work because they can be really fiddly to debug without repetitively modifying the workflow.

Were the secrets ever not null? Can you try adding [`secrets: inherit`](https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow)?

**Comment by Quillraven** [comment]
That did the trick! Thanks <3
