### ISSUE TITLE
Documentation issue (?)

### ISSUE THREAD

**Issue by jobe-m** [Quillraven/Fleks#58]
In below line the "DeadComponent" is added to an entity:
https://github.com/Quillraven/Fleks/blob/06e095062d0363f4a6796369b7b3e0b474590635/ReadMe.md?plain=1#L579

But earlier in line 572 the family is created as "noneOf" DeadComponent:
https://github.com/Quillraven/Fleks/blob/06e095062d0363f4a6796369b7b3e0b474590635/ReadMe.md?plain=1#L572

Question: In my understanding the family listener will not react.
In order to make the family listener react on creation and removal of that entity the "DeadComponent" should not be added. Is that right? So line 579 should be deleted?
https://github.com/Quillraven/Fleks/blob/06e095062d0363f4a6796369b7b3e0b474590635/ReadMe.md?plain=1#L576

**Comment by Quillraven** [comment]
You are right in my opinion but I still the listener might still get triggered in this case because first the `MoveComponent` is added and at that point in time the entity does not have the `DeadComponent` yet, so the listener might get triggered.

I will try that out and no matter what, I will update the example when transferring that to the wiki. Thanks for noticing that!

**Comment by Quillraven** [comment]
I quickly tried that and actually the example doesn't compile in KMP because `FamilyListener` is not an interface, it is a class in KMP. I think it is better to merge those two examples in something more meaningful like that:

```kotlin
class MyFamiliyListener : FamilyListener(
    allOfComponents = arrayOf(MoveComponent::class),
    noneOfComponents = arrayOf(DeadComponent::class)
) {
    override fun onEntityAdded(entity: Entity) {
        println("add")
    }

    override fun onEntityRemoved(entity: Entity) {
        println("remove")
    }
}

fun main() {
    val world = world {
        components {
            add(::MoveComponent)
            add(::DeadComponent)
        }

        families {
            add(::MyFamiliyListener)
        }
    }

    // this will notify the listener via its onEntityAdded function
    val entity = world.entity {
        add<MoveComponent>()
        add<DeadComponent>()
    }
    // this will notify the listener via its onEntityRemoved function
    world.remove(entity)
}
```

The listener is not getting fired that way because they are called AFTER the entity configuration is applied. I think this makes sense.

When I do not add the DeadComponent then add and remove are called accordingly.

As mentioned, I will update that in the wiki soon.

Thanks again for the feedback!

**Comment by jobe-m** [comment]
Cool! The new example looks good. I also checked the wiki. I guess how the family listener now works is how it should work. 

Regarding "firing" of the family listener:
I intentionally thought that specifying/creating an entity

``` kotlin
    val entity = world.entity {
        add<MoveComponent>()
        add<DeadComponent>()
    }
```

is an atomic operation - especially when adding the components.

If the above family listener would fire because the "MoveComponent" is added first this would create a ton of hidden problems with the family listeners.
Image you have a lot components and add them in random order to an entiry (add them as you work on the code). It would be hard to understand and debug why some configured family listeners would fire. (At least for devs not so familiar with Fleks.) If you do not like to fire some family listeners than you need to adjust the order of the added components until the family listeners (magically) do not fire. That would be a nightmare ;)
So making the "world.entity" somehow an atomic operation in regards to the family listeners would make handling of the family listeners easier and less error-prone IMHO.
