### ISSUE TITLE
More dynamic world and entity building

### ISSUE THREAD

**Issue by chrispytoes** [Quillraven/Fleks#83]
My game is heavily based on large amounts of content, and as such, I'm using a combination of config files and a SQLite database to manage it all. On top of that, I also want my game to have good mod support, so I really need a way to do things dynamically like adding component `onAdd` and `onRemove` listeners, or adding components to entities without access to their exact types.

For instance, this doesn't work, as it complains that not enough type information is given:
```
abstract class GameComponent<T>: Component<T> {
    abstract fun onComponentAdded(entity: Entity)
    abstract fun onComponentRemoved()
}

private val gameComponents: MutableList<GameComponent> = mutableListOf()

world {
  components {
    gameComponents.forEach {
      onAdd(it.type()) { entity, component ->
        it.onComponentAdded(entity)
      }
      onRemove(it.type()) { entity, component ->
        it.onComponentRemoved()
      }
    }
  }
}
```

Or this:
```
val someComponents: MutableList<Component<*>> = mutableListOf()
        
world.entity { entity ->
    someComponents.forEach {
        entity += it
    }
}
```

How big of a breaking change would that be to make things like this possible? I basically want to build my own "world builder" object that I can pass around to various places that add new features to the world, and then build it all at once and start it. The entity building problem I can solve by adding an abstract method to `GameComponent` to delegate adding the component, but I'm stuck on adding component listeners dynamically.

**Comment by Quillraven** [comment]
Hi,

can you have a look at the currently open PR and the new `loadSnapshotOf` function? That might solve yourr problem with adding components dynamically without access to their exact types.

About your componen onAdd/onRemove question:

I am not sure if I like to add that directly to our current world  builder because in my opinion you lose the type-safety because you cannot really use reified types in your approach, right? 
I also have a question for you because in 2.x I removed the listener approached and changed it to "hooks" and with that change I also only allowed one hook per component type because it made sense for the - imo - typical use-case for special init/cleanup logic for a component (like Box2D). But if I understand you correctly, you need more than one hook per component?

I have a different proposal, please let me know about your feedback. In my games I usually have special functions to spawn entities and since Fleks 2.x you really add component instances to your entity instead of types that are then created via reflection. That way it is up to the user how he wants to create those instances and e.g. make pooling for some components while doing the normal creation approach for other components.

In your case I could imagine that you create your own `ComponentFactory` or whatever you want to call it, add it as a dependency to your world and use it for component creation/removal.

Here is an example of how I usually create entities (in this case a player):
```kotlin
fun World.spawnPlayer(x: Float, y: Float): Entity {
    val assets = this.inject<Assets>()
    val physicWorld = this.inject<PhysicWorld>()
    val rayHandler = this.inject<RayHandler>()

    return this.entity {
        it += Player()
        it += CameraLock()
        it += Move(3f)
        val boundary = Boundary(x, y, 0.8f, 0.8f)
        it += boundary
        it += Physic.of(physicWorld, boundary, BodyType.DynamicBody, it, MysticGarden.b2dPlayer)
        it += Light.pointLightOf(rayHandler, Color(1f, 1f, 1f, 0.7f), 5f..6.5f, boundary, it[Physic].body)
        it += Animation.of(assets, RegionName.HERO_DOWN, 0f)
        it += Render(sprite(x, y, it[Animation].firstFrame, 1.5f, 1.5f))
    }
}
```

I can then create a player like this:
```
 val (_, playerX, playerY) = map.startLocation
world.spawnPlayer(playerX, playerY)
```

You also see that I have a Box2D world and RayHandler as dependency in my world which I can access in such methods via `inject`.

Now for your scenario, instead of writing things like `it += Player()` you could have your own class to handle custom component logic and do something like:

```kotlin

fun World.spawnPlayer(x: Float, y: Float): Entity {
    val cmpFactory= this.inject<ComponentFactory>()

    return this.entity {
        it += cmpFactory.create<YourCustomComponent>()
    }
}
```

Inside `create` you can trigger your own listeners and other custom logic that you require. 

This is just a quick idea and don't know if it makes sense to you. It has the downside that when you remove components or configure your entities afterwards, you always need to use your component factory to correctly trigger your listeners.

Let me know if this helps and if not, then we can of course add your request functionality and add component hooks with an "unsafe" variant that does not use a reified type. I think I called those functions usualy `...Wildcard` so it might be called `onAddWildcard` / `onRemoveWildcard`.


Also, if you have time I'd appreciate it if you can make a PR for it yourself and I just review it and merge it, since my time at the moment is limited, sorry :/

If you want to wait for me then don't expect this within this or next week. It will be more like ~1 month for that change and a new version release.

**Comment by chrispytoes** [comment]
@Quillraven
> But if I understand you correctly, you need more than one hook per component?

The main reason I need this functionality is because I eventually want to allow mods to add listeners for their own components that I have no access to.

For entity initialization, I'm currently using a similar approach to encapsulate the logic, and it will continue to work with mods as long as I always delegate the actual component attaching operation to the mod, however it would be more convenient if I could abstract the real types away and attach them internally. The snapshot methods look interesting and I'll explore what I can do with that. I was actually looking for a way to serialize and deserialize the entire world state and this looks like it will help with just that.

That all being said, I think I just realized a much simpler solution as I was typing this. I can just pass the `WorldConfiguration` to my mods to let them modify the world in any way they need upon initialization. So yeah I think that about solves it all for me. 🦆

**Comment by jobe-m** [comment]
Regarding serialization of `snapshot` and `snapshotOf` objects.

I am currently looking into that and found that due to the nature of the Component setup in Fleks it is not possible to use `kotlinx.serialization` for anything like `Component<*>`. JSON does not like the Star projection. I have done now already some iterations and tried different ways but in the end got either `Star projections in type arguments are not allowed` or `Serializer for class 'Any' is not found` error messages which I couldn't solve. It just looks like the needed type information is lost when trying to serialize an array of components (output of the snapshot functions). I tried some Polymorphic serialization attempts but stopped somewhere in the middle as it just got too complicated and my time too short for going through all that documentation.

As I am using Korge I went with the Json module of KorIO and wrote my own serializer and deserializer for Component objects. Luckily it doesn't add too much boilerplate code to the components. It will eventually be released soon in <https://github.com/korlibs/korge-fleks>. I hope in the next couple of days :-)

Currently it looks like that:

```kotlin
data class PositionShape(
    var x: Double = 0.0,
    var y: Double = 0.0,
    var width: Double = 0.0,
    var height: Double = 0.0,

    // further testing
    var entity: Entity = nullEntity,
    var string: String = "testString",
    var nullString: String? = null,
    var notNullString: String? = "hello world",
    var boolean: Boolean = false,
    var entities: MutableMap<String, Entity> = mutableMapOf("one" to Entity(2), "two" to Entity(42)),

) : Component<PositionShape>, SerializeFleksComponent {
    override fun type(): ComponentType<PositionShape> = PositionShape
    companion object : ComponentType<PositionShape>()

    /**
     * Function to get properties via deserialization.
     * Unfortunately types of properties cannot be mixed within one decodeComponent call.
     */
    override fun decodeFromJson(v: FleksJsonComponent) {
        v.decodeComponent(::x, ::y, ::width, ::height)
        v.decodeEntityComponent(::entity)
        v.decodeComponent(::string)
        v.decodeComponent(::nullString, ::notNullString)
        v.decodeEntityMapComponent(::entities)
        v.decodeComponent(::boolean)
    }

    /**
     * Function which is used to serialize properties of a component.
     * Add all properties which shall be serialized.
     */
    override fun encodeToJson(b: StringBuilder) {
        b.encodeComponent(componentName(), ::x, ::y, ::width, ::height, ::entity, ::string, ::nullString, ::boolean, ::notNullString, ::entities)
    }
}
```

**Comment by Quillraven** [comment]
Hm, I can convert it to JSON without any issue in LibGDX it seems:
![image](https://user-images.githubusercontent.com/93260/219872463-1dfd2a9f-49c2-4c73-b468-f916933656c2.png)

Just a quick&dirt try in debug mode. I get the snapshot and take the first entry and its third component, which is a Move component and convert it to JSON, which gives me a valid JSON string.

I could imagine that this is related to kotlinx serialization and most likely the have some typical Kotlin typesafety build in. Does this article help? https://stackoverflow.com/questions/64155561/kotlinx-serialization-how-to-circumvent-reified-typeargs-for-deserialization

**Comment by jobe-m** [comment]
Might be that my problem is that I have to run the serialization under Kotlin Multiplatform (because of Korge) and KMP is missing some nice JVM class annotations... The serialization plugin for Kotlin multiplatform seems to be limited in features compared to JVM. I guess the same story as with Fleks 1.0 and Korge ;-)
