### ISSUE TITLE
Basic Example Request

### ISSUE THREAD

**Issue by jonBarcus** [Quillraven/Fleks#96]
Hello!

I wanted to submit a request for a very simple written guide for starting ECS from scratch with Fleks.

No need to get in to any graphics or anything.  It'd be incredibly helpful to understand how to set up the structure.

I have an idea for an ECS but can't code it up.

The game has a **world**.

A **world** has **regions**.

A **region** has **locations**.

**Locations** can have **objects**.

**Objects** can be animate or inanimate and can be moved between locations and/or manipulated/viewed.

Appreciate your consideration (and love the Youtube videos)!

**Comment by Quillraven** [comment]
Hi,

I am not 100% sure what you are trying to achieve, sorry. Do you want to write your own ECS? Or do you want to use Fleks for your described scenario?

In general, I personally wouldn't try to force everything into an ECS. From your description, I would probably design the world,regions and locations without an entity. Not exactly sure what you are trying to achieve but sounds a little bit like a Quadtree structure that you want to implement.

The objects can be entities with components if you want to go for that design.

But again, it really depends on what you are trying to achieve. Some games are more suited for ECS while others aren't IMHO. Use the approach that feels most comfortable for you.

Also, if this is just a general "discussion" then it is better to create a discussion instead of an issue ;)

But let me know if that already helped or if I understood something wrong.

**Comment by Quillraven** [comment]
Closed due to inactivity
